language: r
warnings_are_errors: true
sudo: required
# cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: oldrel
      env: NOT_CRAN=false
    - os: linux
      r: release
      env: NOT_CRAN=true
    - os: osx
      r: release
      env: NOT_CRAN=true
    - os: linux
      dist: bionic
      r: devel
      env: NOT_CRAN=false


notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - kcazelle@uoguelph.ca

before_install:
    - echo $SPECIESPLUS_TOKEN > .Renviron
    - cat .Renviron

after_success:
  - Rscript -e 'covr::codecov()'
