language: r
warnings_are_errors: true
sudo: required
cache: packages


matrix:
  include:
    - os: linux
      r: oldrel
      env: NOT_CRAN=false
      r_check_args: "--no-vignettes"
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      r_check_args: "--no-vignettes"


notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - kcazelle@uoguelph.ca

r_packages:
  - covr

before_install:
    - echo $SPECIESPLUS_TOKEN > .Renviron
    - echo 'NOT_CRAN = "true"' >> .Renviron
    - cat .Renviron

after_success:
  - Rscript -e 'covr::codecov()'
